dragon = 'Agni'
disp_mode = 'Default'
disp_compare = False
bnbOverride = False
leniency = 3
skill_coefficient = 1
attack_rate = 1
additional_time = 0 # interpretted as an additive % increase
initial_time = 10 # seconds
bound_method = 'Experimental' #'Accurate', 'None', 'Experimental, Super Experimental'(NOTE:not implemented currently)
queue_strat = 'depth'
include_string = True