dragon = 'Phoenix(2H)'
disp_mode = 'Skill'
bnbOverride = False
leniency = 0
skill_coefficient = 1
attack_rate = 1
additional_time = 0 # interpretted as an additive % increase
initial_time = 10 # seconds
bound_method = 'Experimental' #'Accurate', 'None', 'Experimental, Super Experimental'(NOTE:not implemented currently)
queue_strat = 'depth'
include_string = True